- pkg/api/endpoint/findings.go
The "Find Findings" endpoint was returning a response like the one
below, wrapping the finding object under a field named "finding":
```
{
"finding": {
"id": "...",
"issue": {...},
"target": {...},
}
}
```
This does not match with what was defined in the API specification.
The correct thing to do is to return directly the finding directly as the root object:
```
{
"id": "...",
"issue": {...},
"target": {...},
}
```
> Modify Find Findings endpoint to comply with swagger definition

- db/sql/V1.48__add_disabled_for_global_programs_table.sql
- pkg/api/persistence.go
- pkg/api/program.go
- pkg/api/service/middleware/global/global.go
- pkg/api/service/middleware/global/programs.go
- pkg/api/service/middleware/global/programs_test.go
- pkg/api/store/cdc/proxy.go
- pkg/api/store/global/global.go
- pkg/api/store/global/programs.go
- pkg/api/store/gprograms.go
This PR allows disable global programs by adding `disabled` flag to the `global_programs_metadata` table.
The implementation is exactly the same as the `autosend` flag.
Show program:
```
vulcan-api-cli -H $VULCAN_HOST --key $VULCAN_TOKEN show programs --team_id $VULCAN_TEAM_ID --program_id web-scanning | jq
{
"id": "web-scanning",
"name": "Web Scanning",
"global": true,
"schedule": {
"cron": "0 8 15 * *"
},
"autosend": false,
"disabled": false,
"policy_groups": [
{
"group": {
"id": "web-scanning-global",
"name": "web-scanning-global",
"description": "assets scanned by web scanners",
"options": "",
"assets_count": 1
},
"policy": {
"id": "web-scanning-global",
"name": "web-scanning-global",
"description": "Default set of checktypes related with web scanning",
"settings_count": 1
}
}
]
}
``` …
> Allow disable global programs

- pkg/api/store/cdc/db.go
- pkg/api/store/cdc/proxy.go
- pkg/api/store/cdc/proxy_test.go
This PR removes the previous default limit (10) for number of CDC log events that could be processed by the background goroutine that handles distributed transactions.
Instead, each time the background goroutine is awaken it will try to process all events that are available, executing them sequentially and deleting them if successful.
> Remove default size limit for CDC events processing per execution

- pkg/api/store/assets.go
- pkg/api/store/assets_test.go
- pkg/api/store/cdc/dto.go
- pkg/api/store/cdc/parser.go
- pkg/api/store/cdc/parser_test.go
- pkg/api/store/cdc/proxy.go
- pkg/api/store/outbox.go
- pkg/api/store/outbox_test.go
- pkg/api/store/team_test.go
- pkg/api/vulndb.go
- pkg/vulnerabilitydb/vulnerabilitydb.go
- pkg/vulnerabilitydb/vulnerabilitydb_test.go
This PR adds modifications to Vulcan API in order to handle and trigger a distributed transaction for the VulnerabilityDB once a new asset is created in Vulcan. This, along with the transaction triggered from the operations that imply asset deletion, will make Vulcan API and VulnDB assets/targets data to be in sync.
Also adds handling of `UpdateAsset` operation which might trigger a deassociation for the tag-team in Vulnerability DB, as well as the creation of the new tag if the update operation includes an identifier modification.
> Handle distributed CreateAsset transaction for Vulnerability DB

- pkg/api/store/global/policies.go
This PR disables vulcan-retirejs check from _Default_, _Sensitive_ and _Redcon_ global policies.
> Disable vulcan-retirejs check

- pkg/api/store/global/policies.go
This PR disable the check vulcan-vulners in all the policies.
> Disable vulcan-vulners checks in all the policies

- pkg/api/store/global/policies.go
Disable the "vulcan-tls" check due to [Mozilla's Cipherscan](https://github.com/mozilla/cipherscan) being unmaintained and [not supporting TLS 1.3](https://github.com/mozilla/cipherscan/pull/169). This causes the check to always report that TLS 1.3 is not supported by the servers regardless of whether or not that is actually the case. Insecure ciphers are already reported by the "vulcan-nessus" check as part of the SSL/TLS plugins (e.g. "[SSL Weak Cipher Suites Supported](https://www.tenable.com/plugins/nessus/26928)" or "[SSL/TLS Deprecated Ciphers Unsupported](https://www.tenable.com/plugins/nessus/132675)") in the [General family](https://www.tenable.com/plugins/nessus/families/General).
> Disable "vulcan-tls" check

- pkg/api/assets_group.go
- pkg/api/store/global/groups.go
- pkg/api/store/global/policies.go
- pkg/api/store/global/programs.go
New global groups, policies and programs have been created in order to scan the assets discovered by the CP:
* The `cp-global` group contains all the assets present in its local group that are not present in the `Default`, `Sensitive` or the redcon local group. 
* The global policy is a copy of the redcon one.
* The global program has been scheduled to run every Wednesday at 6am UTC.
Tested in dev, contact me to show you.
_Note: I think it would be a big improvement to refactor the global entities to be defined in runtime using configuration files instead (e.g. YAML). Probably nobody else except us care about the Redcon or the CP global entities._
> Create global program to scan CP discovered assets

- .travis.yml
- Dockerfile
- go.mod
This PR bumps the version of the following dependencies:
- Flyway
- Alpine
- go version
> Bump docker file dependency versions

- pkg/api/endpoint/assets_test.go
- pkg/api/persistence.go
- pkg/api/service/assets.go
- pkg/api/store/asset_annotations.go
- pkg/api/store/asset_annotations_test.go
- pkg/api/store/assets.go
- pkg/api/store/assets_test.go
- pkg/api/store/cdc/proxy.go
- postman/vulcan.postman_collection.json
This PR refactors the the logic of the persistence layer handling the CRUD operations of the asset annotations. This refactor it's needed as a previous step to being able to implement CDC for the assets (including their annotations). The concrete modifications are:
- Now all the CRUD operations over assets (or asset annotations) end up calling the same methods, for creating, modifying or deleting assets.
- The logic for checking if the annotations of an asset belong to the authorized team of the user calling the endpoints of the asset annotations, are improved in order to avoid a race condition that could make the check to fail.
- Some test for the asset annotations storage layer have been added.
- Some comments about some posible concurrency problems when modifying assets were added, so …
> Refactor annotations

- pkg/api/store/asset_annotations_test.go
- pkg/api/store/assets.go
- pkg/api/store/assets_test.go
- pkg/api/store/cdc/dto.go
- pkg/api/store/cdc/parser.go
- pkg/api/store/outbox.go
- pkg/api/store/outbox_test.go
- pkg/api/store/team.go
- pkg/api/store/team_test.go
This PR homogenizes the data sent to the outbox when any CRUD operation over
asset. Concretely, it ensures that every time an asset is added, updated or
deleted, all the data about the asset is enqueued in the outbox. It also
removes some race conditions that could case the data sent to the outbox to be
incorrect.
These modifications are a prerequisite for implementing event sourcing over an
event bus for the vulcan assets.
Notice that this PR is based on [this](https://github.com/adevinta/vulcan-api/pull/59) other PR, so even though is ready to be reviewed, it will need to be rebased to master after that PR is merged.
Bellow you can find the list of all the methods that perform CRUD operations
over assets, and then, for each method a high level description of the
modifications this PR …
> Assets cdc

- pkg/api/service/assets.go
- pkg/api/service/assets_test.go
Return detailed metrics around the asset creation for the /discovery endpoint. 
The idea is to return (asynchronously) the exact numbers of assets that during the processing were:
Created
Skipped (that is, didn't need any processing)
Updated
Purged
Dissociated
This requirement is needed to be able to keep historically track of the fluctuations of discovered assets over time.
This is something that is already implemented client-side in Redcon (code) but cannot be replicated with the current implementation of the /discovery endpoint. If Redcon were to use the /discovery pipeline, we would automatically lose these metrics and these insights.
This PR creates five new metrics and pushes them only when they are greater than zero.
The metrics created are the following:
* …
> Push new metrics for the discovery endpoint

- pkg/api/persistence.go
- pkg/api/store/assets.go
- pkg/api/store/assets_test.go
- testdata/fixtures/asset_group.yml
- testdata/fixtures/assets.yml
The endpoint (/team/{team_id}/assets) that retrieves the list of assets from a team does not return the correct list of groups when an asset is marked as non-scannable.
If the asset is marked as non-scannable, the global groups do not appear in the list of groups of the asset.
In addiction, the endpoint that retrieves a group's assets (/team/{team_id}/groups/{group_id}/assets) does not return non-scannables assets when the group is a global group.
The endpoints now return scannable and non-scannable assets.
Please, before merging this PR it's necessary to check with @julianvilas  in order to avoid any undesired effect on the services that use the affected endpoints.
> Return non scannable assets in DisjoinAssetsInGroups

- go.mod
- go.sum
This PR upgrades gosaml2 dependency in order to fix associated vulnerabilities:
- [CVE-2020-7711](https://avd.aquasec.com/nvd/cve-2020-7711)
> Upgrade gosaml2

- pkg/asyncapi/kafka/client.go
- pkg/testutil/kafka.go
This PR fine tunes a couple of minor points in regards of the Kafka implementation:
- Kafka client push: Avoids the client to be able to block for ever waiting for a message delivery confirmation.
- Kafka test utils:
- Improves randomization of topic names generation in order to avoid collisions during tests [due to non atomic create/delete topics methods]
- Fixes infinite loop when trying to create a topic which already exists. Returns error instead.
> Fine tune Kafka implementation

- cmd/vulcan-cli/cmd/assets.go
This PR adds a new command to the vulcan-cli that allows to download all the assets, or only the ones with a given asset type, to a local file.
> Add the assets command to the vulcan-cli

- pkg/api/asset.go
- pkg/api/asset_test.go
- pkg/api/service/assets_test.go
- pkg/vulnerabilitydb/vulnerabilitydb.go
A user can add an asset through the UI (and hence through the API) with a malformed identifier, for example, an AWS account ARN with a space in the middle:
`arn:aws:iam:: 012345678900:root`
This causes the outbox CDC to stop working as the subsequent request to the vulnerabilitydb-api to propagate the action fails:
```
component=CDC error=\"<html><body><h1>400 Bad request</h1>\\nYour browser sent an invalid request.\\n</body></html>\\n\" id=93995f78-025e-413e-99d4-d047a4198bd7 action=DeleteAsset retries=20\n","stream":"stderr","time":"2023-05-03T09:05:32.744982511Z"
```
This PR adds two types of controls:
- The first one is a check to avoid creating assets with malformed identifiers
- The second one is to query escape the strings when we make requests to vulcandb.
> Malformed asset identifier makes outbox CDC to stop processing

- .github/dependabot.yml
This repository has many dependabot PRs not merged.
Because of the current dependabot configuration we are missiong our
own dependencies (i.e. github.com/adevinta/vulcan-scan-engine.
This pr removes this limitation.
> Remove dependabot limit

- .travis.yml
- Dockerfile
- cmd/vulcan-cli/cmd/users.go
- go.mod
This PR does 2 things: 
* Bumps the version of go to 1.21
* Adds a new command to the `vulcan-cli` tool
The new command `users` generates a file with the usernames of all the users in all the teams in Vulcan, both members and owners, and with the emails included in the recipients of each team. The generated file contains the list of unique users and emails, sorted  lexicographically.
> Add users command

- go.mod
- go.sum
Starting with the go language family 1.21, the string `1.21' [is not a valid go version ](https://go.dev/doc/toolchain#version) . The travis build was working because the version of go was properly set at the travis.yaml file, but the version in the go.mod is wrong and causing the [dependabot not being able to check for updates](https://github.com/adevinta/vulcan-api/network/updates/714641478)
> Use the proper go version 1.21.0

- Dockerfile
Error message when running build.sh:
```
Step 22/24 : COPY --link config.toml run.sh .
When using COPY with more than one source file, the destination must be a directory and end with a /
```
Docker version:
```
$ docker --version
Docker version 24.0.5, build 24.0.5-0ubuntu1
```
> Dockerfile build breaks on step 22 due to a missing slash

- README.md
- pkg/api/service/tickets.go
- pkg/api/service/tickets_test.go
- Allow to setup `*` for onboarded_teams to activate tracker for all the teams.
- Only for admins or observers
> Allow configure tracker for all the teams
